In [10]:
!pip install numpy

   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ------------------------- -------------- 8.1/12.8 MB 55.7 MB/s eta 0:00:01
   ---------------------------------------- 12.8/12.8 MB 54.5 MB/s eta 0:00:00



[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
import numpy as np

In [8]:
x=np.array([[    1, 25000,   300,  1200,    10],
       [    2, 32000,   450,  1500,    15],
       [    3, 28000,   380,  1100,     8],
       [    4, 41000,   500,  1600,    20],
       [    5, 35000,   420,  1400,    12],
       [    6, 27000,   360,  1300,     9],
       [    7, 39000,   480,  1700,    18],
       [    8, 30000,   400,  1250,    14],
       [    9, 45000,   550,  1800,    25],
       [   10, 33000,   410,  1450,    11]])

In [30]:
y=np.sum(x[:,1])
print(y)

335000


In [31]:
# Which store recorded the **highest sales**?
y=np.argmax(x[:, 1])
print(y)

8


In [32]:
# Which store recorded the **highest sales**?
inventory= x[:, 3]
y= np.sum(inventory < 1300)
print(y)

3


In [33]:
# Retail Data – Business Questions (for `retail_data`)

**Assumed columns:** `[StoreID, Sales, Customers, Inventory, Returns]`

## Basic Performance Analysis
1. What is the **total revenue** generated across all stores?
2. Which store recorded the **highest sales**?
3. Which store recorded the **lowest sales**?
4. What is the **average daily sales** per store?
5. How many stores achieved sales **above ₹35,000**?

## Customer Insights
6. Which store had the **highest customer footfall**?
7. What is the **average number of customers** per store?
8. How many stores have **more than 450 customers**?
9. Which store has the **lowest customer count**?
10. Is there any store where **high sales do not correspond to high customers**?

## Inventory & Returns Analysis
11. What is the **total inventory** across all stores?
12. Which store has the **highest inventory stock**?
13. How many stores have **inventory less than 1300 units**?
14. Which store has the **highest return rate** (returns ÷ inventory)?
15. Which stores have **returns greater than 15 units**?

## Sales & Customer Correlation
16. Is there a **positive correlation** between sales and customers?
17. Which store has **high customer visits but low sales**?
18. Which store has **low customers but high sales**?
19. How many stores have **sales per customer above ₹90**?
20. Which stores could **benefit from customer acquisition campaigns** (low customers, high inventory)?

## Profitability & Growth
21. If profit margin is **20% of sales**, what is the **profit per store**?
22. Which store has the **highest profit**?
23. Which store has the **lowest profit**?
24. If sales increase by **10% next month**, what are the **new sales figures**?
25. How will **total profit** change with the 10% sales increase?

## Operational Strategy
26. Which stores need **inventory restocking** based on sales and current stock?
27. Which stores show **high returns percentage** and might require **quality checks**?
28. Which store is the **best performer overall** (sales, customers, inventory turnover)?
29. Which store is the **worst performer overall**?
30. Which stores can be considered for **expansion** based on strong sales and customer metrics?

SyntaxError: invalid character '÷' (U+00F7) (51575950.py, line 23)

In [40]:
##Which store recorded the **lowest sales**?
y=np.argmin(x[:, 1])+1
y


np.int64(1)

In [44]:
##### What is the **average daily sales** per store
sales = x[:, 1]
y=np.mean(sales)
y

np.float64(33500.0)

In [46]:
#### How many stores achieved sales **above ₹35,000**?
y=sum(x[:,1]>35000)
y

np.int64(3)

In [48]:
### Which store had the **highest customer footfall**?
np.argmax(x[:,2])+1

np.int64(9)

In [50]:
####7. What is the **average number of customers** per store?
y= np.mean(x[:,2])
y

np.float64(425.0)

In [53]:
####8.How many stores have **more than 450 customers**?
y=np.sum(x[:,2]> 450)
y

np.int64(3)

In [55]:
###9. Which store has the **lowest customer count**?
y=np.argmin(x[:,2])+1
y

np.int64(1)

In [56]:
#### Is there any store where **high sales do not correspond to high customers**?


In [2]:
# 10. Is there any store where **high sales do not correspond to high customers**?


NameError: name 'x' is not defined

In [12]:
sal = x[:,1].mean()
cus = x[:,2].mean()
mis = x[(x[:,1] > sal) & (x[:,2] < cus)]
mis

array([[    5, 35000,   420,  1400,    12]])

In [57]:
####11. What is the **total inventory** across all stores?
np.sum(x[:,3])

np.int64(14300)

In [59]:
####12. Which store has the **highest inventory stock**?
np.argmax(x[:,3])+1

np.int64(9)

In [63]:
##### How many stores have **inventory less than 1300 units**?
x[:,3] < 1300
y

array([ True, False,  True, False, False, False, False,  True, False,
       False])

In [14]:
####14. Which store has the **highest return rate** (returns ÷ inventory)?
y= (x[:,4]) / (x[:,3])
x.argmax()+1

np.int64(42)

In [15]:
###15. Which stores have **returns greater than 15 units**?
y =x[(x[:,4]) > 15]
y

array([[    4, 41000,   500,  1600,    20],
       [    7, 39000,   480,  1700,    18],
       [    9, 45000,   550,  1800,    25]])

In [17]:

###16. Is there a **positive correlation** between sales and customers?

In [19]:
###17. Which store has **high customer visits but low sales**?

In [21]:
y = x[:,2].mean()
u = x[:,1].mean()
z= x[(x[:,2] >y) & (x[:,1] < u)]
z

array([[    2, 32000,   450,  1500,    15]])

In [23]:
####18. Which store has **low customers but high sales**?
first = x[:,2].mean()
sec = x[:,1].mean()
res = x[(x[:,2] < first) & (x[:,1] > sec)]
res

array([[    5, 35000,   420,  1400,    12]])

In [24]:
###19. How many stores have **sales per customer above ₹90**?
res = x[:,1] / x[:,2]
new = np.sum(res > 90)
new

np.int64(0)

In [25]:
###20. Which stores could **benefit from customer acquisition campaigns** (low customers, high inventory)?


In [27]:
###21. If profit margin is **20% of sales**, what is the **profit per store**?
res = 0.20 * x[:,1]
res

array([5000., 6400., 5600., 8200., 7000., 5400., 7800., 6000., 9000.,
       6600.])

In [28]:
#### 22. Which store has the **highest profit**?
(x[:,1] * 0.20).argmax()+1

np.int64(9)

In [30]:
# ##23. Which store has the **lowest profit**?
(x[:,1] * 0.20).argmin()+1

np.int64(1)

In [31]:
### 24. If sales increase by **10% next month**, what are the **new sales figures**?
x[:,1] * 0.10

array([2500., 3200., 2800., 4100., 3500., 2700., 3900., 3000., 4500.,
       3300.])

In [32]:
### 25. How will **total profit** change with the 10% sales increase?
(x[:,1] * 0.10) + x[:,1]

array([27500., 35200., 30800., 45100., 38500., 29700., 42900., 33000.,
       49500., 36300.])

In [33]:
### 26. Which stores need **inventory restocking** based on sales and current stock?
sal = x[:,1].mean()
ret = x[:,4].mean()
res = x[(x[:,1] > sal) & (x[:,4] < ret)]
res

array([[    5, 35000,   420,  1400,    12]])

In [34]:
#### 27. Which stores show **high returns percentage** and might require **quality checks**?
aver = x[:,4].mean()
res = x[(x[:,4] > aver)]
res

array([[    2, 32000,   450,  1500,    15],
       [    4, 41000,   500,  1600,    20],
       [    7, 39000,   480,  1700,    18],
       [    9, 45000,   550,  1800,    25]])

In [35]:
#### 28. Which store is the **best performer overall** (sales, customers, inventory turnover)?

In [36]:
### 29. Which store is the **worst performer overall**?


In [37]:
# 30. Which stores can be considered for **expansion** based on strong sales and customer metrics?
a = x[:,1].mean()
b = x[:,2].mean()
res = x[(x[:,1] > a) & (x[:,2] > b)]
res

array([[    4, 41000,   500,  1600,    20],
       [    7, 39000,   480,  1700,    18],
       [    9, 45000,   550,  1800,    25]])